import jsonlines

# t = record.copy()
# del t['input_txt_to_use']
# predictor([t])


[l for l in jsonlines.open(data_path + "/" + dev_test, "r")]

# Get length of the list of dictionaries
# [len(x['input_txt_to_use'].split('</s>'))-1 for x in restructured_records]



{"evidence": [{"content": ["Algebraic logic_sentence_0", "Lindenbaum\u2013Tarski algebra_sentence_1",
                           "Lindenbaum\u2013Tarski algebra_sentence_6", "Lindenbaum\u2013Tarski algebra_sentence_3",
                           "Algebraic logic_cell_0_1_1", "Algebraic logic_cell_0_2_1", "Algebraic logic_cell_0_3_1",
                           "Algebraic logic_cell_0_4_1", "Algebraic logic_cell_0_5_1", "Algebraic logic_cell_0_6_1",
                           "Algebraic logic_cell_0_7_1", "Algebraic logic_cell_0_8_1", "Algebraic logic_cell_0_9_1"],
               "context": {"Algebraic logic_sentence_0": ["Algebraic logic_title"],
                           "Lindenbaum\u2013Tarski algebra_sentence_1": ["Lindenbaum\u2013Tarski algebra_title"],
                           "Lindenbaum\u2013Tarski algebra_sentence_6": ["Lindenbaum\u2013Tarski algebra_title"],
                           "Lindenbaum\u2013Tarski algebra_sentence_3": ["Lindenbaum\u2013Tarski algebra_title"],
                           "Algebraic logic_cell_0_1_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_2_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_3_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_4_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_5_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_6_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_7_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_8_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"],
                           "Algebraic logic_cell_0_9_1": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                          "Algebraic logic_header_cell_0_0_1"]}}, {
                  "content": ["Algebraic logic_cell_0_1_0", "Algebraic logic_cell_0_2_0", "Algebraic logic_cell_0_3_0",
                              "Algebraic logic_cell_0_4_0", "Algebraic logic_cell_0_5_0", "Algebraic logic_cell_0_6_0",
                              "Algebraic logic_cell_0_7_0", "Algebraic logic_cell_0_8_0", "Algebraic logic_cell_0_9_0"],
                  "context": {"Algebraic logic_cell_0_1_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_2_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_3_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_4_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_5_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_6_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_7_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_8_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"],
                              "Algebraic logic_cell_0_9_0": ["Algebraic logic_title", "Algebraic logic_section_4",
                                                             "Algebraic logic_header_cell_0_0_0"]}}], "id": 7389,
 "claim": "Algebraic logic has five Logical system and Lindenbaum\u2013Tarski algebra which includes Physics algebra and Nodal algebra (provide models of propositional modal logics).",
 "label": "REFUTES", "annotator_operations": [{"operation": "start", "value": "start", "time": "0"},
                                              {"operation": "Now on", "value": "?search=", "time": "1.62"},
                                              {"operation": "search", "value": "Algebra Logic", "time": "55.915"},
                                              {"operation": "Now on", "value": "Algebra i Logika", "time": "58.458"},
                                              {"operation": "search", "value": "algebra logical system",
                                               "time": "75.851"},
                                              {"operation": "Now on", "value": "undefined", "time": "77.252"},
                                              {"operation": "search", "value": "Lindenbaum", "time": "95.919"},
                                              {"operation": "Now on", "value": "Lindenbaum", "time": "96.709"},
                                              {"operation": "search", "value": "lindenbaaum-tarski", "time": "112.075"},
                                              {"operation": "Now on", "value": "undefined", "time": "113"},
                                              {"operation": "hyperlink", "value": "Algebraic logic", "time": "126.503"},
                                              {"operation": "Now on", "value": "Algebraic logic", "time": "127.87"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_sentence_0",
                                               "time": "139.588"},
                                              {"operation": "Page search", "value": "logical system", "time": "177.52"},
                                              {"operation": "hyperlink", "value": "Lindenbaum\u2013Tarski algebra",
                                               "time": "198.201"},
                                              {"operation": "Now on", "value": "Lindenbaum\u2013Tarski algebra",
                                               "time": "198.831"}, {"operation": "Highlighting",
                                                                    "value": "Lindenbaum\u2013Tarski algebra_sentence_1",
                                                                    "time": "229.376"}, {"operation": "Highlighting",
                                                                                         "value": "Lindenbaum\u2013Tarski algebra_sentence_6",
                                                                                         "time": "243.39"},
                                              {"operation": "Highlighting",
                                               "value": "Lindenbaum\u2013Tarski algebra_sentence_3", "time": "254.119"},
                                              {"operation": "back-button-clicked", "value": "back-button-clicked",
                                               "time": "309.012"},
                                              {"operation": "Now on", "value": "Algebraic logic", "time": "309.107"},
                                              {"operation": "search", "value": "five", "time": "319.153"},
                                              {"operation": "Now on", "value": "5 (disambiguation)", "time": "320.853"},
                                              {"operation": "back-button-clicked", "value": "back-button-clicked",
                                               "time": "326.901"},
                                              {"operation": "Now on", "value": "Algebraic logic", "time": "326.989"},
                                              {"operation": "Page search", "value": "five", "time": "331.075"},
                                              {"operation": "hyperlink", "value": "sentential logic",
                                               "time": "369.843"},
                                              {"operation": "Now on", "value": "Propositional calculus",
                                               "time": "370.894"},
                                              {"operation": "back-button-clicked", "value": "back-button-clicked",
                                               "time": "372.489"},
                                              {"operation": "Now on", "value": "Algebraic logic", "time": "372.578"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_1_0",
                                               "time": "374.293"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_2_0",
                                               "time": "375.079"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_3_0",
                                               "time": "375.978"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_4_0",
                                               "time": "376.906"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_5_0",
                                               "time": "377.955"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_6_0",
                                               "time": "378.868"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_7_0",
                                               "time": "379.584"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_8_0",
                                               "time": "380.466"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_9_0",
                                               "time": "381.396"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_1_1",
                                               "time": "440.289"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_2_1",
                                               "time": "440.919"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_3_1",
                                               "time": "441.889"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_4_1",
                                               "time": "442.479"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_5_1",
                                               "time": "443.149"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_6_1",
                                               "time": "444.967"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_7_1",
                                               "time": "446.181"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_8_1",
                                               "time": "447.299"},
                                              {"operation": "Highlighting", "value": "Algebraic logic_cell_0_9_1",
                                               "time": "449.401"},
                                              {"operation": "finish", "value": "finish", "time": "559.284"}],
 "challenge": "Multi-hop Reasoning",
 "input_txt_model": "Algebraic logic has five Logical system and Lindenbaum\u2013Tarski algebra which includes Physics algebra and Nodal algebra (provide models of propositional modal logics). </s>  In [[Mathematical_logic|mathematical logic]], algebraic logic is the reasoning obtained by manipulating equations with free variables. </s> Algebraic logic </s> [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Modal_algebra|Modal algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Interior_algebra|Interior algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[MV-algebra|MV-algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Cylindric_algebra|Cylindric algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Boolean_algebra|Boolean algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Heyting_algebra|Heyting algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Boolean-valued_model|Complete Boolean algebra]], [[Polyadic_algebra|polyadic algebra]], [[Predicate_functor_logic|predicate functor logic]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Monadic_Boolean_algebra|Monadic Boolean algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Combinatory_logic|Combinatory logic]], [[Relation_algebra|relation algebra]]. </s> Logical system is [[Intuitionistic_logic|Intuitionistic]] propositional logic ; Logical system is First-order logic with [[Equality_(mathematics)|equality]] ; Logical system is [[First-order_logic|First-order logic]] ; Logical system is [[Clarence_Irving_Lewis|Lewis]]'s [[Modal_logic|S4]] ; Logical system is [[Set_theory|Set theory]] ; Logical system is [[\u0141ukasiewicz_logic|\u0141ukasiewicz logic]] ; Logical system is Lewis's [[S5_(modal_logic)|S5]], [[Monadic_predicate_logic|monadic predicate logic]] ; Logical system is Classical [[Sentential_logic|sentential logic]] ; Logical system is Modal logic [[Normal_modal_logic|K]]. </s>  In [[Mathematical_logic|mathematical logic]], the Lindenbaum\u2013Tarski algebra (or Lindenbaum algebra) of a [[Model_theory#Definition|logical theory]] T consists of the [[Equivalence_class|equivalence classes]] of [[Sentence_(mathematical_logic)|sentences]] of the theory (i.e., the [[Quotient|quotient]], under the [[Equivalence_relation|equivalence relation]] ~ defined such that p ~ q exactly when p and q are provably equivalent in T). </s>  The Lindenbaum\u2013Tarski algebra is considered the origin of the modern [[Algebraic_logic|algebraic logic]]. </s>  The Lindenbaum\u2013Tarski algebra is thus the [[Quotient_(universal_algebra)|quotient algebra]] obtained by factoring the algebra of formulas by this congruence relation.",
 "input_txt_to_use": "Algebraic logic has five Logical system and Lindenbaum\u2013Tarski algebra which includes Physics algebra and Nodal algebra (provide models of propositional modal logics). </s>  In [[Mathematical_logic|mathematical logic]], algebraic logic is the reasoning obtained by manipulating equations with free variables. </s> Algebraic logic </s> [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Modal_algebra|Modal algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Interior_algebra|Interior algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[MV-algebra|MV-algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Cylindric_algebra|Cylindric algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Boolean_algebra|Boolean algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Heyting_algebra|Heyting algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Boolean-valued_model|Complete Boolean algebra]], [[Polyadic_algebra|polyadic algebra]], [[Predicate_functor_logic|predicate functor logic]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Monadic_Boolean_algebra|Monadic Boolean algebra]] ; [[Lindenbaum\u2013Tarski_algebra|Lindenbaum\u2013Tarski algebra]] is [[Combinatory_logic|Combinatory logic]], [[Relation_algebra|relation algebra]]. </s> Logical system is [[Intuitionistic_logic|Intuitionistic]] propositional logic ; Logical system is First-order logic with [[Equality_(mathematics)|equality]] ; Logical system is [[First-order_logic|First-order logic]] ; Logical system is [[Clarence_Irving_Lewis|Lewis]]'s [[Modal_logic|S4]] ; Logical system is [[Set_theory|Set theory]] ; Logical system is [[\u0141ukasiewicz_logic|\u0141ukasiewicz logic]] ; Logical system is Lewis's [[S5_(modal_logic)|S5]], [[Monadic_predicate_logic|monadic predicate logic]] ; Logical system is Classical [[Sentential_logic|sentential logic]] ; Logical system is Modal logic [[Normal_modal_logic|K]]. </s>  In [[Mathematical_logic|mathematical logic]], the Lindenbaum\u2013Tarski algebra (or Lindenbaum algebra) of a [[Model_theory#Definition|logical theory]] T consists of the [[Equivalence_class|equivalence classes]] of [[Sentence_(mathematical_logic)|sentences]] of the theory (i.e., the [[Quotient|quotient]], under the [[Equivalence_relation|equivalence relation]] ~ defined such that p ~ q exactly when p and q are provably equivalent in T). </s>  The Lindenbaum\u2013Tarski algebra is considered the origin of the modern [[Algebraic_logic|algebraic logic]]. </s>  The Lindenbaum\u2013Tarski algebra is thus the [[Quotient_(universal_algebra)|quotient algebra]] obtained by factoring the algebra of formulas by this congruence relation."}
